import Link from "next/link";
import { notFound } from "next/navigation";
import { Shell } from "@/components/Shell";
import { getNews, listNews } from "@/lib/news";
import { CopyLinkButton } from "@/components/CopyLinkButton";

export default async function NewsDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params; const item = await getNews(id); if (!item) notFound(); const related = (await listNews({ category: item.category })).filter((other) => other.id !== item.id).slice(0, 3);
  return <Shell><main className="main news-detail-main"><Link className="back-link" href="/newsportal">← Back to NewsPortal</Link><article className="news-detail-card"><div className="news-detail-kicker"><span className="news-chip">{item.category}</span><span>{item.verificationStatus === "publisher_feed" ? "✓ Publisher attributed" : "✓ Verified"}</span><span>{new Intl.DateTimeFormat("en-IN", { dateStyle: "medium", timeStyle: "short" }).format(new Date(item.publishedAt))}</span></div><h1>{item.headline}</h1><p className="news-detail-summary">{item.summary}</p><div className="news-detail-meta"><span>By {item.author || item.publisher}</span><span>{item.readingMinutes} min read</span><span>{item.geography}</span></div>{item.videoUrl && <div className="news-video-embed"><iframe src={item.videoUrl.replace("watch?v=", "embed/")} title={`Video for ${item.headline}`} loading="lazy" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowFullScreen /></div>}<div className="news-detail-body"><p>This is a concise NewsPortal briefing. The original publisher owns the full report and remains the source of record. Follow the link below for the complete article and any updates.</p><div className="button-row"><a className="button button-primary" href={item.canonicalUrl} target="_blank" rel="noreferrer">Read full story ↗</a><CopyLinkButton /></div></div></article><section className="related-news"><div className="section-heading"><div><span className="eyebrow">Keep reading</span><h2>Related {item.category} stories</h2></div></div><div className="news-grid">{related.map((other) => <Link className="news-card" href={`/newsportal/${other.id}`} key={other.id}><span className="news-chip">{other.category}</span><h3>{other.headline}</h3><p>{other.summary}</p><span className="news-source">{other.publisher} · Read story ↗</span></Link>)}</div></section></main></Shell>;
}
