"use client";

import Link from "next/link";
import { useMemo, useRef, useState } from "react";
import type { NewsCategory, NewsItem, NewsProvider } from "@/lib/news-types";
import { newsCategories } from "@/lib/news-types";

function timeAgo(value: string) { const hours = Math.max(0, Math.floor((Date.now() - new Date(value).getTime()) / 3600000)); return hours < 1 ? "Just now" : hours === 1 ? "1h ago" : `${hours}h ago`; }
function NewsCard({ item, saved, onSave }: { item: NewsItem; saved: boolean; onSave: (id: string) => void }) {
  return <article className="news-card"><div className="news-card-top"><span className="news-chip">{item.category}</span><span className="news-source">{item.verificationStatus === "publisher_feed" ? "✓ Publisher feed" : "✓ Verified"}</span></div><Link href={`/newsportal/${item.id}`}><h3>{item.headline}</h3><p>{item.summary}</p></Link><div className="news-card-meta"><span>{item.publisher} · {timeAgo(item.publishedAt)}</span><span>{item.readingMinutes} min read</span></div><div className="news-card-actions"><span className="news-tag">{item.geography}</span>{item.videoUrl && <span className="news-tag video-tag">▶ Video</span>}<button className={`save-news ${saved ? "saved" : ""}`} onClick={() => onSave(item.id)} type="button" aria-label={saved ? "Saved news story" : "Save news story"}>{saved ? "★ Saved" : "☆ Save"}</button></div></article>;
}

export function NewsPortal({ initialItems, initialSaved, providers }: { initialItems: NewsItem[]; initialSaved: string[]; providers: NewsProvider[] }) {
  const [items, setItems] = useState(initialItems); const [saved, setSaved] = useState(initialSaved); const [query, setQuery] = useState(""); const [category, setCategory] = useState("All"); const [geo, setGeo] = useState("All"); const [videoOnly, setVideoOnly] = useState(false); const searchRef = useRef<HTMLInputElement>(null);
  const filtered = useMemo(() => items.filter((item) => (!query || [item.headline, item.summary, item.publisher, ...item.tags, ...item.topics].join(" ").toLowerCase().includes(query.toLowerCase())) && (category === "All" || item.category === category) && (geo === "All" || item.geography.includes(geo)) && (!videoOnly || Boolean(item.videoUrl))), [category, geo, items, query, videoOnly]);
  const top = filtered[0]; const india = filtered.filter((item) => item.geography.includes("India")).slice(0, 3); const global = filtered.filter((item) => item.geography === "Global").slice(0, 3); const videos = filtered.filter((item) => item.videoUrl).slice(0, 3);
  function save(id: string) { setSaved((current) => current.includes(id) ? current : [...current, id]); void fetch(`/api/news/${id}/save`, { method: "POST" }); }
  return <div className="news-portal-shell">
    <div className="news-heading"><div><span className="eyebrow">NextUp intelligence · live tech signal</span><h1>NewsPortal</h1><p>High-signal technology news from India and the world, with the source always one click away.</p></div><div className="news-live"><i /> Live feed <span>Updated now</span></div></div>
    <section className="news-command" aria-label="News command center"><div className="news-command-copy"><span className="eyebrow">The technology pulse</span><h2>Know what changed before it changes your next move.</h2><p>Follow the ideas, companies, tools, and markets shaping the technology industry without opening ten different tabs.</p><div className="news-actions"><a className="button button-light" href="#latest">Read latest <span>↓</span></a><a className="button button-quiet" href="#videos">Watch briefings <span>▶</span></a><button className="button button-quiet" type="button" onClick={() => searchRef.current?.focus()}>Search news <span>/</span></button></div></div><div className="news-orbit" aria-label="Live news signal visualization"><div className="orbit-ring ring-one" /><div className="orbit-ring ring-two" /><div className="orbit-core"><strong>{items.length}</strong><span>live stories</span></div><i className="orbit-node node-one" /><i className="orbit-node node-two" /><i className="orbit-node node-three" /></div></section>
    <div className="news-stat-grid"><div><span>Live stories</span><strong>{items.length}</strong><small>fresh in the feed</small></div><div><span>India signal</span><strong>{items.filter((item) => item.geography.includes("India")).length}</strong><small>local and national tech</small></div><div><span>Video briefings</span><strong>{items.filter((item) => item.videoUrl).length}</strong><small>permitted embeds or links</small></div><div><span>Sources</span><strong>{new Set(items.map((item) => item.publisher)).size}</strong><small>attributed publishers</small></div></div>
    <section className="news-filter-panel" aria-label="News filters"><div className="news-search"><span>⌕</span><input ref={searchRef} value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search stories, companies, topics…" aria-label="Search news" /></div><select value={category} onChange={(e) => setCategory(e.target.value)} aria-label="Filter by category"><option>All</option>{newsCategories.map((item: NewsCategory) => <option key={item}>{item}</option>)}</select><select value={geo} onChange={(e) => setGeo(e.target.value)} aria-label="Filter by geography"><option>All</option><option>India</option><option>Global</option></select><button className={`filter-toggle ${videoOnly ? "on" : ""}`} type="button" onClick={() => setVideoOnly((value) => !value)}>▶ Video only</button></section>
    {top && <section className="news-lead-grid"><article className="news-lead"><div className="news-lead-art"><span>LIVE SIGNAL</span><strong>{top.category}</strong><i /></div><div className="news-lead-copy"><div className="news-card-top"><span className="news-chip">{top.category}</span><span className="breaking-label">{top.isBreaking ? "Breaking signal" : "Top story"}</span></div><Link href={`/newsportal/${top.id}`}><h2>{top.headline}</h2></Link><p>{top.summary}</p><div className="news-card-meta"><span>{top.publisher} · {timeAgo(top.publishedAt)}</span><span>{top.readingMinutes} min read</span></div><div className="button-row"><Link className="button button-primary" href={`/newsportal/${top.id}`}>Open story ↗</Link><button className="button button-secondary" type="button" onClick={() => save(top.id)}>{saved.includes(top.id) ? "★ Saved" : "☆ Save story"}</button></div></div></article><aside className="news-brief-card"><span className="eyebrow">Source control room</span><h3>Fresh signal, attributed.</h3><p>NewsPortal keeps publisher links, timestamps, and source state visible so speed never comes at the cost of trust.</p><div className="brief-line"><span>Freshness</span><strong>Live</strong></div><div className="brief-line"><span>Configured providers</span><strong>{providers.filter((provider) => provider.status === "configured").length}/{providers.length}</strong></div><div className="brief-line"><span>Video policy</span><strong>Permitted embeds</strong></div></aside></section>}
    <section id="latest" className="news-section"><div className="section-heading"><div><span className="eyebrow">Latest signal</span><h2>Stories worth your attention</h2></div><span className="result-count">{filtered.length} stories</span></div><div className="news-grid">{filtered.length ? filtered.map((item) => <NewsCard key={item.id} item={item} saved={saved.includes(item.id)} onSave={save} />) : <div className="news-empty"><strong>No stories match that signal.</strong><p>Try clearing a filter or checking back after the next source refresh.</p></div>}</div></section>
    <section className="news-columns"><div><div className="section-heading"><div><span className="eyebrow">India tech</span><h2>Closer to home</h2></div></div><div className="news-mini-list">{india.length ? india.map((item) => <NewsCard key={item.id} item={item} saved={saved.includes(item.id)} onSave={save} />) : <p className="muted-copy">No India stories in this view.</p>}</div></div><div><div className="section-heading"><div><span className="eyebrow">Global watch</span><h2>Across the industry</h2></div></div><div className="news-mini-list">{global.length ? global.map((item) => <NewsCard key={item.id} item={item} saved={saved.includes(item.id)} onSave={save} />) : <p className="muted-copy">No global stories in this view.</p>}</div></div></section>
    <section id="videos" className="news-video-section"><div className="section-heading"><div><span className="eyebrow">Video desk</span><h2>Watch the signal</h2></div><button className="text-link" type="button" onClick={() => setVideoOnly(true)}>Show video only →</button></div><div className="video-grid">{videos.length ? videos.map((item) => <NewsCard key={item.id} item={item} saved={saved.includes(item.id)} onSave={save} />) : <div className="news-empty"><strong>No permitted videos in this view.</strong><p>Video sources appear here when publishers allow embedding.</p></div>}</div></section>
  </div>;
}
