"use client";

import { useState } from "react";
import type { NewsItem, NewsProvider } from "@/lib/news-types";

export function NewsAdminPanel({ initialProviders, initialReview }: { initialProviders: NewsProvider[]; initialReview: NewsItem[] }) {
  const [providers, setProviders] = useState(initialProviders); const [review, setReview] = useState(initialReview); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  async function sync() { setBusy(true); setMessage(""); const response = await fetch("/api/admin/news/sync", { method: "POST" }); const data = await response.json().catch(() => ({})); setBusy(false); setMessage(response.ok ? `${data.synced ?? 0} new news draft${data.synced === 1 ? "" : "s"} imported. Review before publishing.` : data.error || "News sync failed."); }
  async function decide(id: string, action: "publish" | "archive") { const response = await fetch(`/api/admin/news/${id}/${action}`, { method: "POST" }); if (response.ok) setReview((items) => items.filter((item) => item.id !== id)); else setMessage("The review action could not be completed."); }
  return <section className="news-admin-panel card form-card"><div className="section-heading" style={{ marginTop: 0 }}><div><span className="section-label">NewsPortal operations</span><h2>News source control</h2><p>Review imported stories, inspect provider readiness, and publish only attributed, approved news.</p></div><button className="button button-primary" type="button" onClick={sync} disabled={busy}>{busy ? "Syncing…" : "Sync news sources"}</button></div><div className="provider-list">{providers.map((provider) => <div className="provider-row" key={provider.id}><div><strong>{provider.name}</strong><small>{provider.kind.replace("_", " ")} · {provider.regions.join(" / ")}</small></div><span className={`provider-status ${provider.status}`}>{provider.status.replace("_", " ")}</span><small>Server-side source · {provider.status === "configured" ? "ready" : "add approved source config"}</small></div>)}</div>{review.length > 0 && <><div className="section-heading news-review-heading"><div><span className="section-label">Review queue</span><h2>{review.length} draft{review.length === 1 ? "" : "s"} awaiting approval</h2></div></div><div className="review-list">{review.slice(0, 5).map((item) => <div className="review-card" key={item.id}><div><span className="news-chip">{item.category}</span><h3>{item.headline}</h3><p>{item.summary}</p><small className="news-source">{item.publisher} · <a href={item.canonicalUrl} target="_blank" rel="noreferrer">source ↗</a></small></div><div className="review-actions"><button className="button button-primary" type="button" onClick={() => decide(item.id, "publish")}>Publish</button><button className="button button-danger" type="button" onClick={() => decide(item.id, "archive")}>Archive</button></div></div>)}</div></>}{review.length === 0 && <p className="muted-copy">No news drafts are waiting for review.</p>}{message && <p className="provider-message">{message}</p>}</section>;
}
