import type { Opportunity } from "./types";

// Keep the verification date stable so a restart cannot make a source look
// newly checked when it was not.
const seededAt = "2026-09-29T12:00:00+05:30";

// Source-checked fallback records for local preview and pilot mode. Replace or
// refresh these through Supabase before relying on the feed as a live directory.
export const demoOpportunities: Opportunity[] = [
  {
    id: "opportunity-decentrahack-2",
    title: "DecentraHack 2.0",
    description:
      "A three-round student hackathon focused on agentic AI, blockchain/Web3, and open source. Teams submit an idea, develop a working solution, and present to judges.",
    summary: "Build something useful with a student team and submit by 30 September.",
    category: "Hackathon",
    organizer: "LFDT Student Chapter at PCCOE",
    officialUrl: "https://decentrahack-2-0.devpost.com/",
    sourceUrl: "https://decentrahack-2-0.devpost.com/",
    sourceType: "official",
    format: "online",
    location: "Online · final presentation in Pune",
    eventStartDate: "2026-10-09T09:30:00+05:30",
    eventEndDate: "2026-10-09T18:00:00+05:30",
    registrationDeadline: "2026-09-30T23:30:00+05:30",
    eligibility: "College students in second year and above; teams of 2 to 4.",
    fees: "Free",
    benefit: "₹15,000+ prize pool and a chance to present a working demo.",
    skills: ["AI", "Open Source", "Blockchain", "Product"],
    tags: ["student-only", "team-based", "pune", "deadline-soon"],
    verificationStatus: "officially_verified",
    aiConfidence: 0.99,
    status: "published",
    lastVerifiedAt: seededAt,
    createdAt: seededAt,
    updatedAt: seededAt,
  },
  {
    id: "opportunity-hackyard-build-2026",
    title: "Hackyard Build 2026",
    description:
      "A 24-hour build opportunity at IIT Guwahati. Applicants can apply solo or with a team and submit an idea first; selected builders are invited to the physical build.",
    summary: "Submit an idea by 10 October for a chance to build at IIT Guwahati.",
    category: "Hackathon",
    organizer: "Hackyard",
    officialUrl: "https://hackyardbuild2026.devpost.com/",
    sourceUrl: "https://hackyardbuild2026.devpost.com/rules",
    sourceType: "official",
    format: "offline",
    location: "IIT Guwahati, Assam",
    eventStartDate: "2026-10-24T09:00:00+05:30",
    eventEndDate: "2026-10-25T18:00:00+05:30",
    registrationDeadline: "2026-10-10T23:45:00+05:30",
    eligibility: "Builders aged 13 and above; students, professionals, and beginners may apply.",
    fees: "Free",
    benefit: "A chance to attend the physical build plus partner credits and awards for selected builders.",
    skills: ["Product", "AI", "Design", "Engineering"],
    tags: ["solo-friendly", "team-based", "iit-guwahati", "india"],
    verificationStatus: "officially_verified",
    aiConfidence: 0.99,
    status: "published",
    lastVerifiedAt: seededAt,
    createdAt: seededAt,
    updatedAt: seededAt,
  },
  {
    id: "opportunity-aicte-pragati-2026",
    title: "AICTE Pragati Scholarship · Degree",
    description:
      "A Government of India scholarship for eligible girl students pursuing a degree in an AICTE-approved technical institution. Applications are submitted through the National Scholarship Portal.",
    summary: "Up to ₹50,000 per year for eligible girl students in technical degree courses.",
    category: "Scholarship",
    organizer: "AICTE · Government of India",
    officialUrl: "https://scholarships.gov.in/All-Scholarships",
    sourceUrl: "https://scholarships.gov.in/public/schemeGuidelines/AICTE/AICTE_2010_G.pdf",
    sourceType: "official",
    format: "online",
    location: "India",
    eventStartDate: null,
    eventEndDate: null,
    registrationDeadline: "2026-10-31T23:59:59+05:30",
    eligibility: "Eligible girl students entering first-year degree or second-year lateral-entry study at an AICTE-approved institution; income and other scheme conditions apply.",
    fees: "Free",
    benefit: "₹50,000 per year, subject to the official eligibility and selection rules.",
    skills: ["Technical Education", "Scholarship", "Undergraduate"],
    tags: ["government", "funding", "women-in-tech", "india"],
    verificationStatus: "officially_verified",
    aiConfidence: 0.99,
    status: "published",
    lastVerifiedAt: seededAt,
    createdAt: seededAt,
    updatedAt: seededAt,
  },
  {
    id: "opportunity-indux-5-2026",
    title: "INDUX 5.0-2026",
    description:
      "An international 24-hour AI hackathon hosted by Vikrant University, Gwalior, where college student teams build solutions for real-world problems across manufacturing, healthcare, safety, security, sustainability, commerce, language, and space.",
    summary: "Build an AI solution with a team and submit by 15 October.",
    category: "Hackathon",
    organizer: "Vikrant University · Gwalior",
    officialUrl: "https://indux-5-0-2026.devpost.com/",
    sourceUrl: "https://indux-5-0-2026.devpost.com/rules",
    sourceType: "official",
    format: "hybrid",
    location: "Online selection · Vikrant University, Gwalior",
    eventStartDate: "2026-11-02T09:00:00+05:30",
    eventEndDate: "2026-11-03T18:00:00+05:30",
    registrationDeadline: "2026-10-15T15:30:00+05:30",
    eligibility: "College students; teams of 2 to 4; international participation is allowed subject to the official rules.",
    fees: "No fee for online registration",
    benefit: "₹2,25,000 cash prize pool, certificates, and visibility for selected solutions.",
    skills: ["AI", "Cybersecurity", "Design", "Robotics"],
    tags: ["student-only", "team-based", "ai", "gwalior"],
    verificationStatus: "officially_verified",
    aiConfidence: 0.99,
    status: "published",
    lastVerifiedAt: seededAt,
    createdAt: seededAt,
    updatedAt: seededAt,
  },
  {
    id: "opportunity-nextgen-hackathon-2026",
    title: "Next Gen Hackathon 2026 · Bengaluru",
    description:
      "A national technology challenge at NextGenExpo'26 for developers, engineers, innovators, and startups. Teams build and present projects across themes including AR/VR, IoT, and machine learning.",
    summary: "Bring a 2–4 person team to a Bengaluru build challenge by 23 October.",
    category: "Hackathon",
    organizer: "RAAIF · NextGenExpo'26",
    officialUrl: "https://next-gen-hackathon.devpost.com/",
    sourceUrl: "https://next-gen-hackathon.devpost.com/",
    sourceType: "official",
    format: "offline",
    location: "Tripura Vasini Palace Grounds, Bengaluru",
    eventStartDate: "2026-10-23T09:00:00+05:30",
    eventEndDate: "2026-10-25T18:00:00+05:30",
    registrationDeadline: "2026-10-23T17:00:00+05:30",
    eligibility: "Participants above the legal age of majority; teams of 2 to 4.",
    fees: "See official event rules",
    benefit: "₹50,000 cash prize pool and a national technology showcase.",
    skills: ["AR/VR", "IoT", "Machine Learning", "AI"],
    tags: ["team-based", "bengaluru", "offline", "technology"],
    verificationStatus: "officially_verified",
    aiConfidence: 0.98,
    status: "published",
    lastVerifiedAt: seededAt,
    createdAt: seededAt,
    updatedAt: seededAt,
  },
  {
    id: "opportunity-innohacks-4-2026",
    title: "Innohacks 4.0",
    description:
      "A national 24-hour hackathon by Innogeeks at KIET Deemed to be University, Delhi-NCR, with an idea-PPT submission round followed by an in-person build for selected teams.",
    summary: "Submit an idea or pitch deck by 30 September for a chance to build in Ghaziabad.",
    category: "Hackathon",
    organizer: "Innogeeks · KIET Deemed to be University",
    officialUrl: "https://innohacks-4.devfolio.co/",
    sourceUrl: "https://innohacks-4.devfolio.co/",
    sourceType: "official",
    format: "offline",
    location: "Ghaziabad, Delhi-NCR",
    eventStartDate: "2026-10-10T09:00:00+05:30",
    eventEndDate: "2026-10-11T18:00:00+05:30",
    registrationDeadline: "2026-09-30T23:59:59+05:30",
    eligibility: "Developers, designers, innovators, and problem-solvers from across India; see the official rules for team requirements.",
    fees: "See official event rules",
    benefit: "A 24-hour build, mentorship, and a chance to showcase a working project.",
    skills: ["AI", "Blockchain", "AR/VR", "IoT"],
    tags: ["idea-round", "team-based", "ghaziabad", "offline"],
    verificationStatus: "officially_verified",
    aiConfidence: 0.97,
    status: "published",
    lastVerifiedAt: seededAt,
    createdAt: seededAt,
    updatedAt: seededAt,
  },
  {
    id: "opportunity-jagriti-hacks-2026",
    title: "Jāgriti Hacks",
    description:
      "A student-only online hackathon focused on ideas for a safer tomorrow, with tracks spanning cybersecurity, DevOps, and machine learning.",
    summary: "Form a four-person student team and submit before the 29 September deadline.",
    category: "Hackathon",
    organizer: "Jāgriti Technologies PVT LTD",
    officialUrl: "https://jagriti-hacks1.devpost.com/",
    sourceUrl: "https://jagriti-hacks1.devpost.com/",
    sourceType: "official",
    format: "online",
    location: "Online",
    eventStartDate: "2026-09-26T00:00:00+05:30",
    eventEndDate: "2026-10-12T12:01:00+05:30",
    registrationDeadline: "2026-09-29T22:00:00+05:30",
    eligibility: "Students only; teams of exactly 4; geographic restrictions apply under the official rules.",
    fees: "Free",
    benefit: "$850 cash prize pool and access to the official participant community.",
    skills: ["Cybersecurity", "DevOps", "Machine Learning"],
    tags: ["student-only", "deadline-today", "team-of-four", "online"],
    verificationStatus: "officially_verified",
    aiConfidence: 0.99,
    status: "published",
    lastVerifiedAt: seededAt,
    createdAt: seededAt,
    updatedAt: seededAt,
  },
  {
    id: "opportunity-aicte-swanath-degree-2026",
    title: "AICTE Swanath Scholarship · Technical Degree",
    description:
      "A government scholarship scheme listed on the National Scholarship Portal for eligible technical-degree students. Confirm the current eligibility, income, and document requirements on the official portal before applying.",
    summary: "Check the National Scholarship Portal for the Swanath application window and eligibility.",
    category: "Scholarship",
    organizer: "AICTE · Government of India",
    officialUrl: "https://scholarships.gov.in/All-Scholarships",
    sourceUrl: "https://scholarships.gov.in/All-Scholarships",
    sourceType: "official",
    format: "online",
    location: "India",
    eventStartDate: null,
    eventEndDate: null,
    registrationDeadline: "2026-10-31T23:59:59+05:30",
    eligibility: "Technical-degree eligibility and welfare conditions are defined by the current official scheme listing.",
    fees: "Free",
    benefit: "Government scholarship support; amount and conditions are defined in the official scheme details.",
    skills: ["Technical Education", "Scholarship", "Undergraduate"],
    tags: ["government", "funding", "india", "technical-degree"],
    verificationStatus: "officially_verified",
    aiConfidence: 0.96,
    status: "published",
    lastVerifiedAt: seededAt,
    createdAt: seededAt,
    updatedAt: seededAt,
  },
];
