import type { NewsItem } from "./news-types";

const now = Date.now();
const hoursAgo = (hours: number) => new Date(now - hours * 3600000).toISOString();
const daysAhead = (days: number) => new Date(now + days * 86400000).toISOString();

export const demoNews: NewsItem[] = [
  { id: "news-ai-india", headline: "India’s AI builders are moving from pilots to production", summary: "A new wave of Indian startups is focusing on dependable AI systems, domain data, and measurable outcomes instead of demos alone.", publisher: "NextUp Briefing", canonicalUrl: "https://example.com/india-ai-builders", sourceUrl: "https://example.com/india-ai-builders", sourceType: "publisher", author: "NextUp editorial desk", publishedAt: hoursAgo(2), updatedAt: null, imageUrl: null, videoUrl: null, category: "AI", tags: ["India", "AI", "startups"], topics: ["applied AI", "founders"], geography: "India", entities: ["Indian startups"], language: "en", readingMinutes: 3, fingerprint: "demo-news-ai-india", verificationStatus: "publisher_feed", status: "published", ingestedAt: hoursAgo(1.5), freshUntil: daysAhead(2), isBreaking: true, isSponsored: false },
  { id: "news-cloud-security", headline: "Cloud security teams are prioritising identity over perimeter controls", summary: "Security leaders are consolidating identity, access, and workload signals as cloud estates become more distributed.", publisher: "NextUp Briefing", canonicalUrl: "https://example.com/cloud-security", sourceUrl: "https://example.com/cloud-security", sourceType: "publisher", author: "NextUp editorial desk", publishedAt: hoursAgo(7), updatedAt: null, imageUrl: null, videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ", category: "Cybersecurity", tags: ["cloud", "identity", "security"], topics: ["zero trust", "cloud infrastructure"], geography: "Global", entities: ["cloud security teams"], language: "en", readingMinutes: 4, fingerprint: "demo-news-cloud-security", verificationStatus: "publisher_feed", status: "published", ingestedAt: hoursAgo(6.5), freshUntil: daysAhead(1), isBreaking: false, isSponsored: false },
  { id: "news-devtools", headline: "Developer tools are becoming the new operating layer for AI teams", summary: "The most useful AI tooling is shifting toward evaluation, observability, and collaboration around real production workflows.", publisher: "NextUp Briefing", canonicalUrl: "https://example.com/developer-tools", sourceUrl: "https://example.com/developer-tools", sourceType: "publisher", author: "NextUp editorial desk", publishedAt: hoursAgo(13), updatedAt: null, imageUrl: null, videoUrl: null, category: "Developer tools", tags: ["developers", "AI", "tools"], topics: ["developer experience", "observability"], geography: "India + Global", entities: ["AI teams"], language: "en", readingMinutes: 5, fingerprint: "demo-news-devtools", verificationStatus: "publisher_feed", status: "published", ingestedAt: hoursAgo(12), freshUntil: daysAhead(3), isBreaking: false, isSponsored: false },
  { id: "news-funding", headline: "Climate and fintech founders are pairing software with hard infrastructure", summary: "Investors are looking for technology businesses that can show distribution, resilience, and a clear route to durable margins.", publisher: "NextUp Briefing", canonicalUrl: "https://example.com/climate-fintech", sourceUrl: "https://example.com/climate-fintech", sourceType: "publisher", author: "NextUp editorial desk", publishedAt: hoursAgo(26), updatedAt: null, imageUrl: null, videoUrl: null, category: "Startups", tags: ["funding", "fintech", "climate"], topics: ["venture capital", "markets"], geography: "India + Global", entities: ["founders", "investors"], language: "en", readingMinutes: 4, fingerprint: "demo-news-funding", verificationStatus: "publisher_feed", status: "published", ingestedAt: hoursAgo(25), freshUntil: daysAhead(4), isBreaking: false, isSponsored: false },
  { id: "news-gadgets", headline: "The next hardware cycle is being designed around repairability", summary: "Device makers are testing longer support windows, modular parts, and lower-friction repair experiences.", publisher: "NextUp Briefing", canonicalUrl: "https://example.com/repairable-hardware", sourceUrl: "https://example.com/repairable-hardware", sourceType: "publisher", author: "NextUp editorial desk", publishedAt: hoursAgo(38), updatedAt: null, imageUrl: null, videoUrl: "https://www.youtube.com/watch?v=aqz-KE-bpKQ", category: "Hardware", tags: ["hardware", "devices", "sustainability"], topics: ["repairability", "product design"], geography: "Global", entities: ["device makers"], language: "en", readingMinutes: 3, fingerprint: "demo-news-hardware", verificationStatus: "publisher_feed", status: "published", ingestedAt: hoursAgo(37), freshUntil: daysAhead(4), isBreaking: false, isSponsored: false },
];
